---
title: "Project 1 - Karen Lopez"
date: "September 18, 2020"
output:
  rmarkdown::github_document:
    toc: true
knit: (function(input, ...){
  rmarkdown::render(
    input,
    output_file="README.md",
    envir=globalenv()
  )})
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project Objectives
Vignettes are explanations of some concept, package, etc. with text, code, and output interweaved.  
This project involves creating a vignette (a .md file that github will render) about reading in data from an API, combining it, and exploring it. You will then create a blog post linking to your vignette.  

## Blog
Once you’ve completed your vignette you should write a brief blog post:  
• explaining what you did in the project and any findings you made  
• You should also reflect on the process you went through for this project. Discuss things like:  
– what would you do differently in approaching the project?  
– what was the most difficult part of the logic and programming for you?  
– what are your big take-aways for future projects?  
• In your blog post, provide a link to your github pages repo  

## Vignette Content Starts Here
# Reading and Summarizing Data from the NHL's API

